import Head from "next/head";
import { Inter } from "@next/font/google";
import { JobSearch } from "@/components/JobSearch/JobSearch";


export default function Home() {
  return (
    <>
      <Head>
        <title>Latest Tech Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto h-screen mt-20">
        <div className="text-center">
          <h1 className="text-5xl font-black">FIND THE LATEST TECH JOBS</h1>
          <h3>Job Board curated for developers</h3>
        </div>
        <JobSearch />
      </main>
    </>
  );
}
